apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
  labels:
    app: nest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: kotlin-app
          image: cerliofaccojr/nest-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: ENVIRONMENT
              value: "dev"
