apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ingress
    repoURL: git@github.com:cerliofaccojr/argo-kubernetes.git
    targetRevision: HEAD
  sources: []
  project: default