apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api/demoservice/
        pathType: Prefix
        backend:
          service:
            name: demo-app
            port:
              number: 80
      - path: /guestbook/
        pathType: Prefix
        backend:
          service:
            name: guestbook
            port:
              number: 80
