apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Ensures the path is rewritten if needed
spec:
  ingressClassName: nginx
  rules:
  - host: localhost  # Replace with your domain if using one
    http:
      paths:
      - path: /api/todo-types
        pathType: Prefix
        backend:
          service:
            name: demo-app
            port:
              number: 80
