apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-app
  labels:
    app: kotlin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotlin-app
  template:
    metadata:
      labels:
        app: kotlin-app
    spec:
      containers:
        - name: kotlin-app
          image: cerliofaccojr/kotlin-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
